### ISSUE TITLE
split repo

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#113]
-service -client -wallet

**Comment by martindale** [comment]
Are these the isolated components we'll be using in a a future Copay?

**Comment by matiu** [comment]
right. -client will be a dependency of Copay (via bower).  A running
instance of -service's URL  will be need to be configured in Copay.

On Tue, Mar 3, 2015 at 1:40 PM, Eric Martindale <notifications@github.com>
wrote:

> Are these the isolated components we'll be using in a a future Copay?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/113#issuecomment-76982135>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
done
