### ISSUE TITLE
IDEA: Support using Bitcoin Core 0.10 directly without using Insight

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#134]
Using `readonly addresses` for new wallets / new addresses.

For importing old wallets,  `-rescan` will be needed.

 
From https://bitcoin.org/en/release/v0.10.0
> One new RPC, importaddress, is added which functions similarly to importprivkey, but instead takes an address or script (in hexadecimal) as argument. After using it, outputs credited to this address or script are considered to be received, and transactions consuming these outputs will be considered to be sent.

> The following RPCs have optional support for watch-only: getbalance, listreceivedbyaddress, listreceivedbyaccount, listtransactions, listaccounts, listsinceblock, gettransaction. See the RPC documentation for those methods for more information.

**Comment by isocolsky** [comment]
Something similar is already on the roadmap. The plan is to have BWS communicating with bitcore instead of with Insight.
