### ISSUE TITLE
IDEA: support importing BIP44 (mycelium / mytrezor) wallets

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#135]
As described at:
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

or even... use BIP44 instead of BIP45 if no offline address creation is needed, and allow
to import-export to myTrezor/myCelium

BIP44 could support offline address creation if each peer-x in a m-n wallet uses `index = n * i + x`

**Comment by isocolsky** [comment]
BIP44 is now the default derivation strategy for new wallets.
