### ISSUE TITLE
idea: implement coinjoin

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#137]
- createTX
  - output: 1bitcoin
  - amount: 1BTC
  - useCoinJoin: true
    - coinJoinToSignTimeout: 1hr
    - coinJoinToBroadcastTimeout: 24hr
    - coinJoinTimeoutPolicy: broadcastWithoutCoinJoin | rejectByServer
-  Transaction will be available to be sign 
  once coinjoin is available, or if timeout is reached,and broadcastWithoutcoinjoin
  is set as policy.
- Coinjoin 'nr of required tx to mix' could be defined at server level
- if `broadcastWithoutcoinjoin` signed sign 2 TXs: with and without coinjoin.
- Once the joined TX is created, there is `coinJoinToBroadcastTimeout` time for signer to sign the TX. If
  txs are not signed (or rejected by "cojoinsigners", coinJoinTimeoutPolicy is used

**Comment by martindale** [comment]
+1.
