### ISSUE TITLE
mycelium wallet my phones boot loader crapped out on me before I could back up my wallet how do I recover my btc #1

### ISSUE THREAD

**Issue by daemon00** [bitpay/bitcore-wallet-service#201]

**Comment by matiu** [comment]
this doen't seem to relate to bitcore-wallet-service.

**Comment by daemon00** [comment]
So I found my wallet but I don't know where to find my private since my
phone has been reset I have proof that its my wallet cause I have an
account which was funded from my wallet before my phone reset its self and
I'm The only one in control of this online account what should I do
