### ISSUE TITLE
Urgent! -  can't access wallet -  error: 'Could not fetch unspend outputs:[object Object]' 

### ISSUE THREAD

**Issue by offerm** [bitpay/bitcore-wallet-service#212]
Hi,

I'm getting the below error for my 2-4 bitcore-wallet wallet.
Getting the same error also with the CoPay app (sharing the same wallet):

C:\workspace_sts\bitcore-wallet\bin>node wallet status
[error] [object Object]
{ code: 'ERROR',
  error: 'Could not fetch unspend outputs:[object Object]' }

**Comment by dabura667** [comment]
clear all proposals and try again.

**Comment by offerm** [comment]
Thanks for coming  back  to me. 
How should i do that?

Sent from Yahoo Mail on Android

**Comment by matiu** [comment]
Could you please try again? BWS public server was rebooted yesterday. I should be OK now.
