### ISSUE TITLE
Copay is not able to fetch outputs or history from insight

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore-wallet-service#229]
I am running my own bws that connects to bitpay insight.
I also have wallets that connect to bitpay bws.

Both of them immediately return with a "this wallet isn't registered on this server" but come up with errors saying "Could not fetch outputs" (this error comes on both wallets when connected to their correct bws.

The fact that they know they aren't registered on each bws tells me that the bws <> copay comms are ok... but both bws use bitpay insight... so I think there is a problem there.

Maybe it's only temporary.

**Comment by matiu** [comment]
Can you try now? There was a networking problem with the server.

**Comment by dabura667** [comment]
Works now. Thanks.

Any details on what went wrong?

**Comment by matiu** [comment]
There was a network issue with the insight server. It was fixed by our
hosting company. thanks!

On Tue, Jun 2, 2015 at 8:42 PM, dabura667 <notifications@github.com> wrote:

> Works now. Thanks.
>
> Any details on what went wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/229#issuecomment-108132650>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
