### ISSUE TITLE
public BWS is down? "couldn't fetch unspent output"

### ISSUE THREAD

**Issue by offerm** [bitpay/bitcore-wallet-service#230]
Hi,

I'm getting this error from Copay wallet.

is the server down?

Thanks

**Comment by troggy** [comment]
Same here

**Comment by matiu** [comment]
This was for testnet only, bitcoind instances went locked with
```
"Safe mode: Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues.
```
it is fixed now.

**Comment by troggy** [comment]
Again same issue. 

Request
````
curl -H "Content-Type: application/json" -X POST -d '{ "addrs": "2N6rBp9SEocRzZZig89AXS9PSr3SMhRns" }' https://test-insight.bitpay.com/api/addrs/utxo
````
sometimes returns ``Server not yet ready. Sync Percentage:NaN``

**Comment by matiu** [comment]
@troggy That one (https://test-insight.bitpay.com/api/addrs/utxo) is not the BWS server, but the public insight testnet insight. Those are not related. Anyways, the public testnet Insight server is up now, you can check the status at:
http://stats.pingdom.com/dm8bfk2t3v6b

**Comment by troggy** [comment]
@matiu Yes, sorry.. I knew that it's Insight. Next time will raise the issue in Insight repo.

Anyway, can you please confirm that the following is working for you?

````
curl -H "Content-Type: application/json" -X POST -d '{ "addrs": "2N6rBp9SEocRzZZig89AXS9PSr3SMhRns" }' https://test-insight.bitpay.com/api/addrs/utxo
````

**Comment by troggy** [comment]
It works from time to time for me.

**Comment by matiu** [comment]
there is a load balancer in top of that api, one of the backend server was
still syncing. If is fixed now. Thanks for the report.


On Mon, Aug 3, 2015 at 11:02 AM, Kosta Korenkov <notifications@github.com>
wrote:

> It works from time to time for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/230#issuecomment-127250244>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
