### ISSUE TITLE
Potential problem: Hacker locks out funds.

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore-wallet-service#235]
Let's say there is a 2 of 3 wallet with keys A B C

A is on a server, automated through bwc
B is on the CTO's cell phone where he checks manually when he gets an email notification from BWS.
C is held by a trusted third party and not actively followed, as sort of a backup.

Server is hacked and hacker gets A. Locks up all funds, and runs a script to send another proposal immediately after it gets rejected.

B wants to be able to create a proposal before A locks them up again, so that he can move the funds to a secure wallet.

Suggestion: Does BWS have failsafe in place to say "If A's txp was just finally rejected / removed by A, he can not create another txp for 1 minute", or something like that? If not, I think it should have some feature like that.

(My other thought was to remove the "locking" feature all together and allow conflicting proposals, and conflicting proposal that's input was spent successfully is automatically purged... but I remember talk here about "what if someone takes the partially signed transaction and signs it later even though their rejected in-app?" etc... so I don't know if we should revisit that, or if a time delay would be best.)

The only time I could see someone legitimately wanting to re-do a proposal quickly is when it is the creator deleting a txp he created less than 1 minute ago ("Oops, I forgot this" type thing)... but if someone just got rejected by everyone, or deletes a txp that already had a reject (pull request pending, I know) then they should be forced to wait 30 seconds - 1 minute so other people have a chance to make a proposal.

**Comment by matiu** [comment]
I believe that in this case (when you now one copayer has been compromissed) the safest / easiest way to proceed is to sweep the wallet from backups, without using BWS.

**Comment by dabura667** [comment]
Currently, is there a tool for sweeping a copay wallet without going through bws?

**Comment by isocolsky** [comment]
I actually agree with @dabura667 on this. One of the goals of BWS was to shield copayers from attacks (spamming, DoS, etc) comming from other copayers. Funds should always go where quorum decides.
Having said this, I am not sure this is a priority right now. Things like better backups and alternative ways to move funds not relying on BWS are more important. Once that is done I would revisit this issue and implement some type of DoS prevention check.
Regarding removing the locks: I don't think there is a way to make this intuitive to the user from a UX point of view. Also, a malicious copayer could spam the server with tx proposals if they are not constrained by available UTXOs. So we would still have to implement some checks.

**Comment by dabura667** [comment]
> Things like better backups and alternative ways to move funds not relying on BWS are more important.

Totally agree.

> Also, a malicious copayer could spam the server with tx proposals if they are not constrained by available UTXOs.

One person can only have one active proposal at a time per utxo. If I am A, and I propose to spend utxo B, I can no longer propose one with B until I rescind the original txp or someone else approves a competing txp and actually broadcasts it.

**Comment by matiu** [comment]
I see the use-case now. sounds good idea to add a (exponential?) 'backoff'
time, when the last copayer's tx was rejected by the quorum. good catch.

On Mon, Jun 8, 2015 at 9:48 AM, dabura667 <notifications@github.com> wrote:

> Things like better backups and alternative ways to move funds not relying
> on BWS are more important.
>
> Totally agree.
>
> Also, a malicious copayer could spam the server with tx proposals if they
> are not constrained by available UTXOs.
>
> One person can only have one active proposal at a time per utxo. If I am
> A, and I propose to spend utxo B, I can no longer propose one with B until
> I rescind the original txp or someone else approves a competing txp and
> actually broadcasts it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/235#issuecomment-109981190>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
@dabura667 Check https://github.com/bitpay/bitcore-wallet-service/issues/235 ? What you think?

**Comment by matiu** [comment]
fixed by #246
