### ISSUE TITLE
Allow programmatic access to wallets without holding keys

### ISSUE THREAD

**Issue by isocolsky** [bitpay/bitcore-wallet-service#236]
It would be useful if wallets had a list of tokens granting access to some parts of the API (e.g. get balance, create addresses, create proposals, reject proposals, react to notifications, etc). Copayers could manage the access list by generating these tokens and passing them to external agents and applications. Changes to the access list (adding and revoking access, modifying access rights, etc)  would have to be accepted by quorum of course.
An extremely simple example would be an agent for address generation. Since this agent would not have access to the funds, it could be hosted in a low security environment. All addresses generated by this agent would be immediately available to copayers via the Copay app.

**Comment by dabura667** [comment]
I just realized this. I think this is similar to my #238 in that it is one type of access permissions.

My thought was to have a 3rd party who will be a signatory + out of band communications for help with backup recovery. ie. a lawyer who you do not want to see all balance and all transaction proposals, but a specific type of transaction proposal will finally be seen by him (ie. "Emergency transaction proposal" etc). But he will not see the tx, only the Hash(tx) that he must sign for ECDSA. He can then verify the hash over phone (or some other out of band) and approve once he has verified the owner's identity.

This is not vital for normal people, but if businesses are to use their own BWS instances with their own Insight-api instances etc. It would be a useful function to have.

Maybe have this special type of signatory only creatable via BWC, but the backup from that signatory is importable to Copay, and there is a simple UI for them.

---------

In this vein, I think there are many possibilities of creating access permissions on various levels for business users.

**Comment by lazerdye** [comment]
I think a simple "watch only" feature could be useful, where an unauthenticated (or token-based) request could check the balance, addresses, and transactions of a wallet. Would there be any security or performance implications if some GET-only requests were added:

/v1/wallets/<peer_id>/
/v1/txhistory/<peer_id>/
/v1/addresses/<peer_id>/

These would be the same as the authenticated requests, but returning data for a specific peer?
