### ISSUE TITLE
error at v1/wallet

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#280]
ERR! Could not compute fees needed to transfer max amount Invalid Argument: Must provide the scriptPubKey for that output!
ERR! Could not compute fees needed to transfer max amount Error
ERR! Could not compute fees needed to transfer max amount     at Error.NodeError (/opt/bws/bitcore-wallet-service/node_modules/bitcore/lib/errors/index.js:20:41)
ERR! Could not compute fees needed to transfer max amount     at Object.module.exports.checkArgument (/opt/bws/bitcore-wallet-service/node_modules/bitcore/lib/util/preconditions.js:14:13)
ERR! Could not compute fees needed to transfer max amount     at new UnspentOutput (/opt/bws/bitcore-wallet-service/node_modules/bitcore/lib/transaction/unspentoutput.js:44:5)
ERR! Could not compute fees needed to transfer max amount     at Transaction._fromMultisigUtxo (/opt/bws/bitcore-wallet-service/node_modules/bitcore/lib/transaction/transaction.js:558:10)
ERR! Could not compute fees needed to transfer max amount     at Transaction.from (/opt/bws/bitcore-wallet-service/node_modules/bitcore/lib/transaction/transaction.js:529:10)
ERR! Could not compute fees needed to transfer max amount     at /opt/bws/bitcore-wallet-service/lib/server.js:717:11
ERR! Could not compute fees needed to transfer max amount     at arrayEach (/opt/bws/bitcore-wallet-service/node_modules/lodash/index.js:1367:13)
ERR! Could not compute fees needed to transfer max amount     at Function.<anonymous> (/opt/bws/bitcore-wallet-service/node_modules/lodash/index.js:3413:13)
ERR! Could not compute fees needed to transfer max amount     at /opt/bws/bitcore-wallet-service/lib/server.js:716:9
ERR! Could not compute fees needed to transfer max amount     at /opt/bws/bitcore-wallet-service/lib/server.js:255:12
ERR! Could not compute fees needed to transfer max amount  { [bitcore.ErrorInvalidArgument: Invalid Argument: Must provide the scriptPubKey for that output!]

**Comment by isocolsky** [comment]
Fixed by https://github.com/bitpay/insight-api/pull/339
