### ISSUE TITLE
Confirm email addresses

### ISSUE THREAD

**Issue by isocolsky** [bitpay/bitcore-wallet-service#290]
Send a confirmation email whenever an email address is associated to a wallet for notifications.

**Comment by mrkent** [comment]
I assume this would be so your backup isn't sent to the wrong email address. If so, it's likely that it would need a 2nd factor from the phone (maybe a code to use as an email reply).

**Comment by matiu** [comment]
No. Emails are only for notifications and also BWS does not know the backup of a wallet so it wouldn't be able to send a backup to an email.
This is only a to safeguard that BWS is sending emails to a confirmed owner of an email address.
