### ISSUE TITLE
Internal Server Error when creating an address in a locked wallet

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#341]
ERR! Err: /v1/addresses/ :undefined:Wallet is locked 
127.0.0.1 2015-09-02T19:20:31.841Z "POST /bws/api/v1/addresses/" 500 28 5016.261 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" 
ERR! Locker server threw error Error: Timeout waiting for lock
ERR! Locker server threw error     at null._onTimeout (/Users/ematiu/devel/bws/node_modules/locker/lib/Lock.js:24:25)
ERR! Locker server threw error     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
ERR! Locker server threw error  [Error: Timeout waiting for lock]

**Comment by isocolsky** [comment]
Closing in favor of #402
