### ISSUE TITLE
Remove socket.io dependency

### ISSUE THREAD

**Issue by isocolsky** [bitpay/bitcore-wallet-service#365]
Implement long-polling for notifications.

**Comment by braydonf** [comment]
Via EventSource: https://developer.mozilla.org/en-US/docs/Web/API/EventSource ?

**Comment by isocolsky** [comment]
For now it's just a manual polling using the notifications endpoint from #382. The notification querying loop is setup in BWC in this method: https://github.com/bitpay/bitcore-wallet-service/pull/390
