### ISSUE TITLE
Can't broadcast

### ISSUE THREAD

**Issue by Qaezel** [bitpay/bitcore-wallet-service#396]
ubuntu@ip-172-31-12-57:~/wallets$ wallet -f mywallet.dat broadcast 8a2b
[error] [object Object]
{ code: 'ERROR', error: 'Error querying the blockchain' }

I have sign txs that aren't getting broadcasted. We have all signed the tx but we are unable to broadcast. Also, all the funds are locked. When you ask the status, it sometimes says 0 locked and sometimes says they are all locked. I am unable to remove the transaction.

**Comment by chinh7** [comment]
Same here. I also experience balance inconsistency when querying via bitcore-wallet-client

**Comment by isocolsky** [comment]
These issues have been resolved. Please reopen if this is not the case for you.

**Comment by maximilliangeorge** [comment]
Has this really been resolved? I'm still having issues.

**Comment by maximilliangeorge** [comment]
Could someone please point me to someplace where i can read how this is resolved? I'm still having these issues. Insight works fine, all other functions work fine, up until broadcast.
