### ISSUE TITLE
Generating an address when the wallet is lock returns status = 500

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#402]
<img width="897" alt="bws_ _node_ _112x29" src="https://cloud.githubusercontent.com/assets/98844/11165684/ff6d03ba-8af4-11e5-8cf5-9224c0685d06.png">

**Comment by isocolsky** [comment]
All operations requiring a lock on a resource will wait for 5 seconds for the lock to be released. Do you think this time needs to be extended (at the risk of timing out on the http request)? In your opinion, is there a more appropriate way to communicate this error to the user than to return a 5xx error?
