### ISSUE TITLE
Installation instructions says "bws" instead of "bitcore-wallet-service"

### ISSUE THREAD

**Issue by toomim** [bitpay/bitcore-wallet-service#408]
The installation instructions says:

```
Install
 npm install bws
 npm start
```

But you actually need:
```
 npm install bitcore-wallet-service
```

Or maybe I'm missing some bigger context here... I haven't actually gotten an installation working yet.

**Comment by dalbelap** [comment]
+1

Or just clone and type "npm start"

**Comment by matiu** [comment]
fixed by https://github.com/bitpay/bitcore-wallet-service/pull/410
