### ISSUE TITLE
Report: Let's Encrypt works beautifully

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore-wallet-service#423]
Prerequisites:
1. A TLD pointing to your server
2. apache2 installed
3. BWS installed and running on normal http and on port 3232 or w/e

Steps:
1. git clone the letsencrypt repo
2. cd into it
3. ./letsencrypt-auto --apache
4. fill out info about your domain(s)
5. Install proxy modding for apache
6. edit the ssl conf in sites-enabled to include reverse proxy connecting /bws/api/ to http://localhost:3232/bws/api/
7. https for Copay <> Apache and http for Apache <> BWS (same machine)

to renew the cert, just run the command again every 90 days.

**Comment by dabura667** [comment]
Perhaps we can recommend this instead (like a free TLD from http://www.dot.tk/ and then free SSL cert from Let's Encrypt) to prevent the many errors that occur on mobile devices when attempting self-signed SSL certs.

**Comment by matiu** [comment]
Thanks for the report, sorry for the very late delay. I will ink this on the readme.
