### ISSUE TITLE
New transactions are not being recorded

### ISSUE THREAD

**Issue by chinh7** [bitpay/bitcore-wallet-service#428]
Transactions sent to Copay wallet in the past 12 hours or so are not shown or reflected on the balance. There seems to be issues with BWS since I'm still able to see those transactions on Insight.

**Comment by NicolasDorier** [comment]
I confirm, same problem.

**Comment by RussianNeuroMancer** [comment]
https://bitpay.github.io/copay-recovery/ should help.

**Comment by NicolasDorier** [comment]
This issue should be close it was a temporary problem of copay's bitcoin service.

**Comment by chinh7** [comment]
This is happening again

**Comment by matiu** [comment]
Could you please check again and reopen the ticket if the problem persist?
We are migrating our bitcoind instance. Thanks and sorry for the
inconvenience.

On Wed, Jan 20, 2016 at 4:15 AM, chinh7 <notifications@github.com> wrote:

> This is happening again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/428#issuecomment-173115515>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
