### ISSUE TITLE
TX_CANNOT_REMOVE Cannot remove this tx proposal during locktime

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/bitcore-wallet-service#447]
The tx proposal was accepted by the copayers but not broadcasted (2-2 wallet, both signatures). After 1 hour I can't remove the TX and it 's still locking funds.

**Comment by isocolsky** [comment]
Take a look at #481. Hopefully it will help reduce the frequency of this problem.

**Comment by isocolsky** [comment]
I'm assuming this is no longer an issue. If you are still experiencing this problem, please reopen.
