### ISSUE TITLE
Bad fee calculation

### ISSUE THREAD

**Issue by JDonadio** [bitpay/bitcore-wallet-service#465]
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/13851807/13153481/1d6b5b9c-d653-11e5-8b41-fb50cec817a9.png)
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/13851807/13153495/379eda48-d653-11e5-93f7-e6897fd11d83.png)

**Comment by isocolsky** [comment]
This is a Copay issue. It should be resolved in 1.9.
