### ISSUE TITLE
Problem with big wallets

### ISSUE THREAD

**Issue by cosmosman** [bitpay/bitcore-wallet-service#471]
Is my server compromised or is there a bug in a bitcore component somewhere?
Since yesterday, every transaction on a particular account end up emptying the wallet.
Here are two problem transactions:
https://blockchain.info/tx/548ea7dadbadb6fee90b5196f4dd106c5cfe58181c050465bc5574ff21ed9097
https://blockchain.info/tx/74a3cb16a8dc5294d20d4f32cf43d2856686162c2e66b9f2463e2b5772c8ed5f

Could it be that BWS is losing the change address? I have no idea what is going on here. 
Please help.

**Comment by cosmosman** [comment]
More information:
I am running bitcore full node, bitcore wallet service and bitcore wallet clients.

**Comment by cosmosman** [comment]
In this transaction: https://blockchain.info/tx/548ea7dadbadb6fee90b5196f4dd106c5cfe58181c050465bc5574ff21ed9097

1JBDphDXqpMKh2X1F4CDLykNPsZfgcLeVE should be the change address, but it doesn't seem to belong to my wallet. The wallet is empty.

**Comment by dabura667** [comment]
What versions are you running on each component?

Do you have any logs?

**Comment by cosmosman** [comment]
I am running version 3.0.0 of bitcore full node (installed 3 days ago).
Bitcore wallet service: 1.3.3
Bitcore wallet client: 1.1.9

Which log do you want?

**Comment by cosmosman** [comment]
I now know for a fact that BWS and BWC are not compromised as far as an attack is concerned.
I know this because I made a checksum of every single javascript file for those modules and their dependencies ahead of deploying them to the server and the checksums have remained unchanged.
I did not checksum bitcore full node.

**Comment by matiu** [comment]
Are you sure the both outputs address are not on the wallet? That's definitely a problem. Can you check for the change address in BWS's mongo database?

**Comment by cosmosman** [comment]
As you can see in the blockchain, the wallet is empty. Going by the last two transactions on the wallet, there should be money in it. I will check BWS's database and see what I find.

**Comment by cosmosman** [comment]
Since the wallet address is public, I decided to take a screen shot before another transaction occurs on it.

**Comment by isocolsky** [comment]
A quick way to check the balance associated with your seed is to use 
https://bitpay.github.io/copay-recovery/

**Comment by cosmosman** [comment]
Current state (before another transaction occurs)
![wallet](https://cloud.githubusercontent.com/assets/17496440/13358065/5c6b27f2-dca5-11e5-954b-4db41776aa53.PNG)

**Comment by matiu** [comment]
"As you can see in the blockchain, the wallet is empty" 
I think you are confused. It is not possible to know which addresses are from your wallet in the blockchain.

**Comment by cosmosman** [comment]
My address is 1Kk9... final balance: zero

**Comment by cosmosman** [comment]
> I think you are confused
I get your point. The wallet balance is still zero though. I will use the copay recovery referenced above.

**Comment by cosmosman** [comment]
The address does belong to the wallet in BWS database. But why is the wallet balance zero?

db.addresses.find({"walletId":"5946c7a4-af86-44f0-be9f-9aaadce00552" , "address":"1JBDphDXqpMKh2X1F4CDLykNPsZfgcLeVE"})
{ "version" : "1.0.0", "createdOn" : 1456465910, "address" : "1JBDphDXqpMKh2X1F4CDLykNPsZfgcLeVE", "walletId" : "5946c7a4-af86-44f0-be9f-9aaadce00552", "isChange" : true, "path" : "m/1/1009", "publicKeys" : [  "02c98283658f1dd2c5b4394797bb3edd29dbd6...." ], "network" : "livenet", "type" : "P2PKH", "hasActivity" : null, "_id" : ObjectId("56cfe7fd2d78135d034e328a") }

**Comment by cosmosman** [comment]
Is there a bitcore API to "repair" the wallet?

**Comment by cosmosman** [comment]
I already tried /v1/addresses/scan with no success. The wallet balance remains zero.

**Comment by cosmosman** [comment]
By the way, I could not use the copay recovery tool because it wants a password. The wallet does not have a password. I created it using the BWS API.

**Comment by matiu** [comment]
Is your bitcore already in sync with the blockchain? Can you check you insight-ui? And check the addresses balance there?

**Comment by matiu** [comment]
)(password is optional on the recovery tool)

**Comment by cosmosman** [comment]
Insight says current sync status is "finished".
I found the address in Insight:
Total Received: 0.00920516 BTC
Total Sent: 0 BTC
Final Balance: 0.00920516 BTC
No. Transactions: 1

I think BWS must somehow not be calculating balance right. 
But everything worked right for days. The wallet has hundreds of transactions, until yesterday when this started happening.

**Comment by cosmosman** [comment]
I investigated further. 

I installed the latest version of BWS and recreated 5 different wallets on it (including the problematic wallet). I then called /v1/address/scan on all of them.
When I queried the wallets for unspent outputs, using BWC, all the wallets correctly returned a list of unspent outputs except the problematic wallet. 

The problematic wallet returns an empty list for unspent outputs, despite the fact that this address: 1JBDphDXqpMKh2X1F4CDLykNPsZfgcLeVE  belongs to it and has unspent output. There are several addresses that belong to that wallet with unspent outputs, most likely up to 0.7btc.

The only difference with the problematic wallet as far as I can tell right now is that it has had a lot of transactions.

**Comment by cosmosman** [comment]
It turns out there is in fact a bug in BWS when your wallet has more than 1000 addresses. I'm surprised I'm the first to run into this issue.

I fixed the issue and now my wallet returns a balance of over 1btc instead of zero.

The issue is with Storage.prototype.fetchAddresses. It returns a maximum of 1000 addresses because of MongoDB's 1000 documents hard limit or queries requiring in-memory sort (https://jira.mongodb.org/browse/SERVER-5374).
I simply took out the sort as it doesn't look like it is needed and that solved the problem.

You either need fix this or post a warning that wallets don't support more than a thousand addresses. I only just started using bitcore a few weeks ago and don't fully know the ramifications of my change, so please look into it and respond.

Thanks

**Comment by dabura667** [comment]
Please change the title of this issue to something like:

"BWS loses track of balance for wallets with over 1000 addresses"

**Comment by matiu** [comment]
Currently BWS handles multiple wallets with 10,000+ addresses, I dont think this is an issue. Also https://jira.mongodb.org/browse/SERVER-5374 is from 2012 and it is closed already.

**Comment by cosmosman** [comment]
The issue I faced was not about multiple wallets with 10,000+ addresses.
The issue was with *1* wallet with over 1,000 addresses.

Matias Alejo Garcia:

**Comment by matiu** [comment]
Are you using you own BWS? Or the public BWS?

**Comment by cosmosman** [comment]
My own. I wrote earlier that I installed the latest version and it also
had the bug.

Matias Alejo Garcia:
