### ISSUE TITLE
It doesn't connect to Insight server

### ISSUE THREAD

**Issue by hectorchu** [bitpay/bitcore-wallet-service#482]
I had to change this.hosts[0] to this.hosts in lib/blockchainexplorers/insight.js to make it work.

**Comment by gabegattis** [comment]
+1 I experience the same problem when running standalone BWS. 

When I log out the error in _initExplorer's socket.on('connect_error') at https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/blockchainmonitor.js#L82 I get

{ [Error: xhr poll error] type: 'TransportError', description: 503 }

**Comment by matiu** [comment]
You mean you had to change this line:

https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/blockchainexplorers/insight.js#L158

It seems it is already fixed. Should be close this issue?

**Comment by gabegattis** [comment]
Yup. That was the line. Master works for me now.
