### ISSUE TITLE
Error estimating fee

### ISSUE THREAD

**Issue by troggy** [bitpay/bitcore-wallet-service#495]
Not sure whether the issue is on Insight side, but I got the following in BWS logs:
````
WARN Insight https://insight.bitpay.com:443/api/utils/estimatefee?nbBlocks=1,2,6 Returned Status: 400 
ERR! Error estimating fee Error querying the blockchain
````

**Comment by troggy** [comment]
Insight response:
````
Method not found. Code:-32601
````

**Comment by dabura667** [comment]
Did you just recently start up your node (the one behind the insight instance)?

Estimate fee will fail until bitcoind has had time to calculate the fee estimates. (You will have to wait a few blocks after you start up bitcoind before it starts working with estimatefee.)

**Comment by troggy** [comment]
That's on insight.bitpay.com

**Comment by troggy** [comment]
Now is something else:
````
WARN Insight https://insight.bitpay.com:443/api/tx/send Returned Status: 400 
ERR! /v1/txproposals/01460455176797b749c5f7-799d-4ada-823e-ef92a44501f9/broadcast/ :500:Error querying the blockchain 
````
