### ISSUE TITLE
version confusion

### ISSUE THREAD

**Issue by dooglus** [bitpay/bitcore-wallet-service#502]
https://www.npmjs.com/package/bitcore-wallet-service tells me that "1.6.1 is the latest of 63 releases", but the code it gives me fails to connect to my insight server. I read the code far enough to track the bug down to this line in `insight.js`:

    var socket = io.connect(this.hosts[0], {

and then discovered that it was fixed 22 days ago here: https://github.com/bitpay/bitcore-wallet-service/commit/8692c068601b89e7f63e210f5b43a058fda4e35b

I don't see any 1.6.1 or newer release or tag in this repository.

So where can I find the 1.6.1 code, and which is the recommended release to use? Is there a newer release, or are people still using 1.6.0?

**Comment by isocolsky** [comment]
Hi! Thank you for reporting. Version 1.7.0 of BWS has been published. If you also use [BWC](https://github.com/bitpay/bitcore-wallet-client), version 2.3.0 has just been published.
