### ISSUE TITLE
confirmations in txhistory have wrong value

### ISSUE THREAD

**Issue by wzrdtales** [bitpay/bitcore-wallet-service#503]
See the following example, we get back from txhistory 83660 instead of 0:

```javascript
{ txid: '5b01534a1597985a2516ce139df97af530f2ce24c449c545b74ab60676bc755c',
  action: 'received',
  amount: 19968764,
  fees: 11236,
  time: 1457266563,
  outputs: 
   [ { amount: 19968764,
       address: 'n2HAqSHJtp1goowcGs4XJg61LArCW88m1R',
       encryptedMessage: undefined,
       message: null } ],
  confirmations: 83660,
  encryptedMessage: undefined,
  message: null,
  hasUnconfirmedInputs: false }
```

Used the latest bws version and node 5.11.0, hope that is engough for you to reproduce I'm in a hurry so just ask if you need more information and  I will add them later.

Edit: now instead of 2 confirmations I recieve 83662 confirmations.
Edit2: now instead of 3 83664 and it was txhistory not notifications.

**Comment by isocolsky** [comment]
Both Insight and Blockr.io are reporting 83k+ confirmations for this tx:

https://test-insight.bitpay.com/tx/5b01534a1597985a2516ce139df97af530f2ce24c449c545b74ab60676bc755c

http://tbtc.blockr.io/tx/info/5b01534a1597985a2516ce139df97af530f2ce24c449c545b74ab60676bc755c

Why do you think it should have less than that?

**Comment by wzrdtales** [comment]
B/c I send a few seconds ago

**Comment by isocolsky** [comment]
Are you sure this is the one you just sent? The date in that tx (`time` field) is GMT: Sun, 06 Mar 2016 12:16:03 GMT

**Comment by wzrdtales** [comment]
Oh, nevermind... sry. For some reason the order reverse doesn't catched anymore, sry for the hassle, and thanks for fast reply :)
