### ISSUE TITLE
Incorrect assumptions for scriptSig limit

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore-wallet-service#505]
https://github.com/bitpay/bitcore-wallet-service/blob/1ce36b674291440d631075edb16a0c81e59fd2a0/lib/model/wallet.js#L80

This says `For compressed keys, m*73 + n*34 <= 496`

But this is not true, as m is irrelevant (practically) for size restrictions, as the max size of the scriptSig total is 10,000 bytes.

The only thing that really matters is n, because there is a restrictive limit on "the size of a single push data to the stack" which is 520 bytes (I think this is what you are talking about with <= 496.)

sources:
Single stack item size limit:
https://github.com/bitcoin/bitcoin/blob/v0.12.1/src/script/script.h#L22
Entire script limit (scriptSig or scriptPubkey)
https://github.com/bitcoin/bitcoin/blob/v0.12.1/src/script/interpreter.cpp#L250

I always thought that the limitations on signer pairs was a UX decision similar to "well, let's assume 15 of 15 multisig is too hard to manage, so don't even bother showing the user"

But I think that BWS should be able to accept anywhere from 1-of-2 all the way to 15-of-15 for multisig.

Coinkite (which recently disappeared) used to offer 15-of-15 for their users.

See also: https://github.com/bitpay/copay/issues/4197

--------------------

# My suggestions:

1. Set the limits to a simple `(m >= 1 && m <= n) && (n >= 1 && n <= 15)`
2. Allow users in Copay to add any combination of m and n, and do not restrict as long as the above conditions are met.
3. Perhaps a toggle under "Advanced Settings" when creating a wallet could say "Choose m and n manually" which when toggled (default is off) would change the Copayer and Signatures inputs from dropdown box to text input box.
4. This way, we can suggest to the user most common combinations, but also allow advanced users to make 15 of 15 etc. if they decide it is necessary.
5. We should test 15 of 15 wallets for bugs.

**Comment by dabura667** [comment]
I think it is very rare. But Coinkite offered any combination of multisig from `(m >= 1 && m <= n) && (n >= 2 && n <= 15)` and I think a lot of their users have come to Copay.

**Comment by dabura667** [comment]
Maybe just fix the limits and not implement in Copay, which forces 15-of-15 user to use BWC or BW CLI to create it.

**Comment by matiu** [comment]
Thanks a lot for the insightful information @dabura667.  The limit in Copay is set only because we think the common use cases are covered. The limit in BWC/S seems to be wrongly enforced, according to the information your are sharing. I agree we should allow all the possible combinations.
