### ISSUE TITLE
Uses of bitcorenode

### ISSUE THREAD

**Issue by carlosfaria94** [bitpay/bitcore-wallet-service#525]
Hi,

What is the point of /bitcorenode and /lib/wsapp.js ?

Because there is a lack of comments.

Thanks

**Comment by isocolsky** [comment]
Hi, /bitcorenode declares BWS as a [Bitcore](https://bitcore.io/api/node) service module.
/lib/wsapp.js is a web-sockets layer for communication with client apps. It is just there for backwards compatibility since all communications are done through long-polling now.
Hope this helps.

**Comment by carlosfaria94** [comment]
Thanks for the response @isocolsky, so I don't need the /bitcorenode for running the BWS, only if I want aggregate as a service in Bitcore full-node, right?

**Comment by isocolsky** [comment]
That's right. You will still need an Insight service for BWS to connect to. You can run your own or you can use BitPay's public instance https://insight.bitpay.com/

**Comment by carlosfaria94** [comment]
Thanks!

**Comment by carlosfaria94** [comment]
@isocolsky and whats the goal of https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/notificationbroadcaster.js ?

I think is never used. Thanks
