### ISSUE TITLE
Get 413 when address space grows too large

### ISSUE THREAD

**Issue by chinh7** [bitpay/bitcore-wallet-service#538]
> WARN Insight https://insight.bitpay.com:443/api/addrs/utxo Returned Status: 413

Looks like Insight starts to reject utxo requests when the payload grows too large. I think there should be a more efficient way to check the wallet balance, like excluding all change addresses after their balances get back to 0.

**Comment by braydonf** [comment]
Also, as the address space grows, it becomes much more efficient to keep a track of a each block, and filter the latest block for relevant addresses and apply those deltas to a database of utxos, balances and txids.
