### ISSUE TITLE
Allow ID to be an option in createTxProposal

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-wallet-service#543]
in should be a valid UUID
(http://stackoverflow.com/questions/7905929/how-to-test-valid-uuid-guid)

**Comment by braydonf** [comment]
This should help with idempotence for creating txs proposals.

**Comment by gabegattis** [comment]
+1  Definitely will help with problems I have dealt with. I'm not sure I would enforce that it had to be a uuid though. In BitPay, we already use content hashes to deal some of these. It would be nice to re-use that hash if possible.

**Comment by matiu** [comment]
After some feedback, we should also consider using:

proposalId = hash(toAmount, toAddress, nonce)

and make `nonce` an optional parameter in createTx (if not given a random one should be used, and returned in the txProposal object).
