### ISSUE TITLE
Cannot send transaction - undefined is not a function

### ISSUE THREAD

**Issue by rlbeckett** [bitpay/bitcore-wallet-service#548]
I'm having trouble with Copay which is unable to send transactions. Every time I click send it returns the error `Could not send payment: undefined is not a function`.

I've traced the problem in BWS to the storeTX function in lib/storage.js where it calls `txp.toObject()`. 

The toObject function uses `_.cloneDeep(this)` but having logged the original object and the cloned object, there are differences:
- The original `changeAddress._id = 579f16dc35fb9276ce1d5264`
- The clone `changeAddress._id = { _bsontype: 'ObjectID', id: [Object] }`

If I replace the lodash `cloneDeep` with `clone` it works fine.  If I replace it with `JSON.parse(JSON.stringify(this))` it also works. Does anyone have any idea what's going wrong with the cloneDeep here?

**Comment by JohnEz** [comment]
I replicated the problem that I think is the same as this, however I get a different error message but from the same place.

I cloned down, bitcore-node, -lib and bitcoin. Created a new node with insight-api, -ui and BWS, and made links where necessary, then ran it on regtest. I generated coins perfectly fine, sent them to my copay wallet (which was connected to my local BWS on testnet) then tried to send them back to an address generated by bitcoind. However I got the error -

```Could not send payment: object [{ "_bsontype": "ObjectID", "id":  [Object]}] is not a valid ObjectId```

It displays what id contains but it was too long for me to paste here. A screenshot is below.

![copayerror](https://cloud.githubusercontent.com/assets/10764897/17813055/a92a0684-6621-11e6-9cfb-552ef43de464.png)

**Comment by bezlogina89** [comment]
![](https://cloud.githubusercontent.com/assets/10764897/17813055/a92a0684-6621-11e6-9cfb-552ef43de464.png)

**Comment by bezlogina89** [comment]
http://www.github.com/)

**Comment by isocolsky** [comment]
That's strange, I can't reproduce this behavior. Which version of MongoDb are you running? @rlbeckett, @JohnEz

**Comment by JohnEz** [comment]
I'm running 3.2.8

**Comment by rlbeckett** [comment]
I'm currently and have for the most part been running version 3.2 but I did roll it back to version 2.6 when I first found the problem a month and that didn't seem to fix it.

Incidentally, the fix I'm currently running is to stop the cloneDeep from recursively going into the BSON object and instead return it as a string is to use the optional 'customizer'.
```
TxProposal.prototype.toObject = function() {
  var x = _.cloneDeep(this, function(value) {
    if (value && value._bsontype) {
      return value.toString();
    }
  });
  x.isPending = this.isPending();
  return x;
};
```

**Comment by rlbeckett** [comment]
I spent quite a bit of time looking into this yesterday and it appears as though the problem is with the Nodejs version. Bitcore-node's requirements restrict which version you can use and I have always been using v0.12.15. I'm further restricted as I'm building for use on Alpine Linux and only certain versions are available on that.

I first double checked MongoDB, using both v3.2.9 and v2.6.9 still had the problem occurring. However when I changed to Nodejs v4.5 the problem stopped occurring. I switched back to Nodejs 0.12.15 and the problem immediately returned. I then also tried v4.3 (the version available on Alpine) and that was fine too.

When switching between node versions I did encounter some some errors seemingly thrown by the zmq module but these were resolved by reinstalling it after each switch. 

So the problem appears to be with Nodejs v0.12.15 or, possibly, with the zmq module running on that node version.

**Comment by matiu** [comment]
Thanks for the update. We should detail in the README that we only support node 4 ATM
(https://github.com/bitpay/bitcore-wallet-service/blob/master/.travis.yml#L15)
