### ISSUE TITLE
HTTPS error: Error connecting to Insight (livenet) @ https://localhost:3001

### ISSUE THREAD

**Issue by deweller** [bitpay/bitcore-wallet-service#553]
I am able to run a bitcoin wallet service successfully without an SSL cert.  But when I attempt to run a bitcoin wallet service using a self-signed certificate, the wallet service returns a 404 error.  Additionally, I see the following error repeatedly in the logs:

`Error connecting to Insight (livenet) @ https://localhost:3001`

Below is my configuration file.

``` json
{
    "https": true,
    "httpsOptions": {
        "cert": "/path/to/cert/cert.pem",
        "key": "/path/to/cert/key.nopass.pem"
    },
    "network": "livenet",
    "port": 3001,
    "services": [
        "bitcoind",
        "bitcore-wallet-service",
        "insight-api",
        "web"
    ],
    "servicesConfig": {
        "bitcoind": {
            "spawn": {
                "datadir": "./data",
                "exec": "/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/bin/bitcoind"
            }
        },
        "bitcore-wallet-service": {
            "bwsPort": 3232
        }
    }
}
```

If I remove the https settings (https and httpsOptions), then the wallet service works as expected over http.

What can I do to make https work?

Thanks.

**Comment by frz-dev** [comment]
Have you created the certificate files?
If not, create them, and then set the path correctly ("/path/to/cert/" is not a valid path :)
If you create the key in the node directory you can use a relative path (e.g. "./key.pem")

You can create your certificate by using the following command:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem`

**Comment by deweller** [comment]
The above file was just an example.  I had paths that pointed to the self-generated cert in my actual config file.

I ended up putting an nginx proxy in front of this with a Let's Encrypt SSL cert.  Thanks.
