### ISSUE TITLE
Wallet not found - lower and upper case wallet ID

### ISSUE THREAD

**Issue by carlosfaria94** [bitpay/bitcore-wallet-service#565]
Hello. I'm with this problem, BWS cannot find my wallet, after successful created. Previously my code is working well but now it's broken - after changing to upper case wallet IDs.

The reason, is that the wallet is created with upper case wallet ID (ex: 747C1D26) and when bws do a GET request for the wallet (/v2/wallets/747c1d26/copayers) with lower case, the bws return a 400 - wallet not found.

I already tested the same code, but with lower cases, and works. With upper cases return wallet not found.

```
verb Wallet created 747C1D26 testnet
::ffff:127.0.0.1 "POST /bws/api/v2/wallets/" 200 51 163.606 "-" - -
verb Notification NewCopayer { walletId: '747C1D26',
verb Notification   copayerId: 'edab1f847697ff2ffcc4414cde9a4ca199371e1a465f12da3900f1e458f4b1b4',
verb Notification   copayerName: ' ' }
::ffff:127.0.0.1 "POST /bws/api/v2/wallets/747C1D26/copayers" 200 1956 196.686 "-" - -
info Client Err: 400 /v2/wallets/747c1d26/copayers <ClientError:WALLET_NOT_FOUND Wallet not found> 
::ffff:127.0.0.1 "POST /bws/api/v2/wallets/747c1d26/copayers" 400 56 54.671 "-" - -
```

I think one solution is `.toLowerCase()` in arguments of the requests, after sending or getting to database, because I think that MongoDB is doing this when storing it, so we need to force it.

**Comment by isocolsky** [comment]
Hi,
I'm not sure I understand the problem. Is BWS/BWC converting your IDs to lower case? Or would you like BWS/BWC to be case insensitive for IDs?

**Comment by carlosfaria94** [comment]
@isocolsky yes, I would like BWS/BWC to be case insensitive for IDs
