### ISSUE TITLE
COPAYER_REGISTERED: Copayer ID already registered on server

### ISSUE THREAD

**Issue by bitjson** [bitpay/bitcore-wallet-service#593]
When the user deletes an incomplete wallet, BWS needs to "release" the wallet, and allow it to be used in the creation of other wallets: https://github.com/bitpay/copay/issues/4899

**Comment by matiu** [comment]
dup: https://github.com/bitpay/bitcore-wallet-service/issues/369

**Comment by isocolsky** [comment]
I don't think the two issues are the same. Issue #369 refers to deleting the wallet remotely when the user deletes it locally. But this issue is about undoing the join action before the wallet is complete.

**Comment by hortonelectric** [comment]
+1 I've seen this issue get swept under the rug a few times now. What's going on, is, quite simply, I have imported a wallet, the server takes too long to respond, so my client times out (meaning the wallet never gets added on the client side) but the server finally does finish the request (way too late) and now, the server has a copy of the wallet, but there's nothing on the client side.

It would be helpful if someone could show me how to retrieve the wallets from the server that should be in my local list. If it's COPAYER_REGISTERED then I should be able to flip a switch and it should show up in my local, period. 

Anybody have any real input?

**Comment by insiderq** [comment]
+1 for the issue
