### ISSUE TITLE
Where's the private key associated with the public address?

### ISSUE THREAD

**Issue by frz-dev** [bitpay/bitcore-wallet-service#599]
Hi,
I'm trying to understand where the private key is stored when creating a new wallet address.

I thought that it corresponded to the walletPrivKey, but if I get the address from that it results to be different from the other one.

So where's the private key I'm looking for?

**Comment by dabura667** [comment]
Derived from xprv using BIP32

**Comment by frz-dev** [comment]
Ok.
Let's say I import a wallet. Then I derive the priv key this way:

`var c = client.credentials
  var xpk = c.getDerivedXPrivKey().toString();`

Is this correct?

Then how do I create the PrivateKey object?
If I try `PrivateKey.fromString(xpk)` it give me an error. So I guess I miss one step.

Let's say my final goal is to retrieve the WIF format of the private key corresponding to the wallet address,
what functions should I use?

**Comment by dabura667** [comment]
`c.getDerivedXPrivKey().derive("m/0/0").privateKey.toWIF()` for first receiving key
`c.getDerivedXPrivKey().derive("m/0/1").privateKey.toWIF()` for second receiving key
`c.getDerivedXPrivKey().derive("m/1/0").privateKey.toWIF()` for first change address key
`c.getDerivedXPrivKey().derive("m/1/1").privateKey.toWIF()` for second change address key

etc etc.

**Comment by frz-dev** [comment]
Many thanks.
It is much more clear now

**Comment by frz-dev** [comment]
Sorry, this is for the receiving and change addresses. 
What about the sending address (i.e. the wallet address)?

**Comment by dabura667** [comment]
No such thing.

**Comment by frz-dev** [comment]
Sorry, I misunderstood :).
Thanks again
