### ISSUE TITLE
[TypeError: xpub.deriveChild is not a function]

### ISSUE THREAD

**Issue by aderiver** [bitpay/bitcore-wallet-service#637]
Hi;

Install the BWS, but when creating an address for my wallet, it always generates this error "TypeError: xpub.deriveChild is not a function"

**Comment by isocolsky** [comment]
Hi there, there's been a recent change in the required version of `bitcore-lib`. Did you try running `npm i` before `npm start`?

**Comment by aderiver** [comment]
Hi

I solved the problem by reinstalling everything

thanks

**Comment by OniSaku1024** [comment]
Hello.
My solution is use a low version nodejs ,like v4.8.4 .
I got this problem in v8.9 ,and it's done after I changed my nodejs version.
