### ISSUE TITLE
How to change port 3232 to 443?

### ISSUE THREAD

**Issue by thosuperman** [bitpay/bitcore-wallet-service#665]
I have tried to change config https://github.com/bitpay/bitcore-wallet-service/blob/master/config.js

Uncomment these lines:
`https: true,
 privateKeyFile: 'private.pem',
 certificateFile: 'cert.pem',`

And change **port: 3232** to **port: 443**

But the bitcore-wallet-service can't start.

Would anyone guide me how to change port 3232 to 443 ?

Thanks so much.

**Comment by dabura667** [comment]
Most likely:

1. Something else is listening to 443. Stop that process.
2. Node does not have permission to listen to 443. See: https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443

**Comment by thosuperman** [comment]
I have used Apache as proxy, receive requests to https://bws.example.com/bws/api to http://localhost:3232/bws/api
