### ISSUE TITLE
Is BWS itself coin-agnostic?

### ISSUE THREAD

**Issue by wrinkl3** [bitpay/bitcore-wallet-service#678]
If I were porting BWS to a (Litcoin-based) altcoin, would I need to make changes in the BWS itself or would rewriting Bitcore-lib suffice?

**Comment by isocolsky** [comment]
This is a good question. BWS was not designed to be coin agnostic. Although it delegates most of the coin-specific functionality to the blockchain explorer (Insight) and bitcore-lib, it is still dependent on at least P2SH and BIP32. So, as long as the target coin supports both these features, you should be ok.

**Comment by wrinkl3** [comment]
Thanks for the reply! I'm assuming the same is also true of the Bitcore
Wallet Client, correct?

**Comment by isocolsky** [comment]
Yes, in addition to Mnemonics (BIP 39),  encrypted paper wallets (BIP 38) and Payment protocol.
Also, keep in mind that test fixtures for both BWS & BWC assume Bitcoin only. There are a lot of hardcoded addresses and raw transactions in the tests.

**Comment by wrinkl3** [comment]
Understood, thank you.

**Comment by mbarek1** [comment]
Compris merci
