### ISSUE TITLE
Low amount solution

### ISSUE THREAD

**Issue by 1alejo0** [bitpay/bitcore-wallet-service#687]
Hello. I have a low ammount of BTC in my wallet. 0.0074btc. 

Under the confirmation of payment there's a yellow square that says amount is too low to spend.

Does this mean that I cannot transfer the 32 dollar I have within the wallet?

If I wait for the price of BTC to go up will I be able to send it to some other wallet?

**Comment by 1alejo0** [comment]
What is the current fee for transactions?

**Comment by matiu** [comment]
Hi, this is not related to Bitcore-wallet-service.
