### ISSUE TITLE
How do I retrieve BCH from my pre-august Bitpay wallet?

### ISSUE THREAD

**Issue by Vilscon** [bitpay/bitcore-wallet-service#704]
Hey guys,

I had my Bitpay wallet with a few BTC before august and I want to retrieve the bitcoin cash. I can't seem to find a way to do so. 

https://blog.bitpay.com/bitcoin-cash-wallet-beta/
This page shows a 'Show my Bitcoin cash' button, but there isn't one in my Bitpay macOS app. It wasn't there with 3.6.2, and isn't available in 3.7.3 either. It isn't available in Copay latest version either, when I import my old wallet and it doesn't show in the Bitpay iOS app.

I also copied my 12-word phrase to BTC.com and tried to use their import tool and it said "No positive bitcoin cash balance found". Oddly enough, there was about 5 BTC in my Bitpay wallet..

So how do I retrieve my BCH?

**Comment by matiu** [comment]
you need to signup for the Beta. Please note this repo is for wallet-service, not for the wallet itself (https://github.com/bitpay/copay).
