### ISSUE TITLE
connection error with bws

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore-wallet-service#706]
**Install BWS from NPM**

Use the following steps to Install BWS from the npmjs repository and run it with defaults.

npm install bitcore-wallet-service
cd bitcore-wallet-service

To change configuration before running, see the Configuration section.

npm start

when i try to fire above command it'll give error like below:

info Using locker server:localhost:3231 
info Using message broker server at http://localhost:3380 
Connection established to mongoDB
info Using message broker server at http://localhost:3380 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3232
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at /root/Digy-Pay-bitcore/node_modules/bitcore-wallet-service/bws.js:87:10
    at /root/Digy-Pay-bitcore/node_modules/bitcore-wallet-service/bws.js:71:14
    at /root/Digy-Pay-bitcore/node_modules/bitcore-wallet-service/bws.js:58:22
    at /root/Digy-Pay-bitcore/node_modules/bitcore-wallet-service/node_modules/async/lib/async.js:251:17
    at done (/root/Digy-Pay-bitcore/node_modules/bitcore-wallet-service/node_modules/async/lib/async.js:132:19)

**Comment by matiu** [comment]
BWS must be already running.  Try `npm stop` first.
