### ISSUE TITLE
How to generate multiple address using bitcore wallet service

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore-wallet-service#709]
I am using bitcore wallet service. which gives the features like create wallet, wallet balance,generate proposal...etc, here is the link of

https://github.com/bitpay/bitcore-wallet-service which i have follow.

But if i want to generate multiple address using bitcore wallet service is it possible. because i can not found any details from the entire documents.

**Comment by matiu** [comment]
use GET /v3/addresses (https://github.com/bitpay/bitcore-wallet-service/blob/master/README.md)
