### ISSUE TITLE
WALLET_LOCKED error?

### ISSUE THREAD

**Issue by rickygu** [bitpay/bitcore-wallet-service#711]
![screen shot 2017-10-17 at 10 04 11 pm](https://user-images.githubusercontent.com/1279365/31701714-2ad3a786-b387-11e7-8cc6-7474bf36ee7f.png)

I'm getting this error from BWS in my copay client. What's causing this error?

**Comment by matidu7777** [comment]
Same here:-( 

" Could not create transaction" 
"WALLET_LOCKED: Wallet is locked"

What that means? I lost some money now because of the exchange rate. That is not accaptable! 

What is the issue?

**Comment by benma** [comment]
Same issue - looks like an urgent problem. All BWS users might be affected.

**Comment by matiu** [comment]
please follow https://github.com/bitpay/copay/issues/6930, we are investigation the issue
