### ISSUE TITLE
Wallet locked

### ISSUE THREAD

**Issue by matidu7777** [bitpay/bitcore-wallet-service#712]
Hello 
This morning I want to transfer funds from my Bitpay Wallet to my Bitpay card. I received the error message: 

" Could not create transaction" 
"WALLET_LOCKED: Wallet is locked"

What that means? I lost some money now because of the exchange rate. That is not accaptable! 

What is the issue?

**Comment by matiu** [comment]
WALLET_LOCKED means that the wallet is been updated or certain operation is done on the wallet (like address scanning ) and you need to wait a bit to use it.
