### ISSUE TITLE
2-sig wallet

### ISSUE THREAD

**Issue by bbob1234** [bitpay/bitcore-wallet-service#738]
I have created a 2-sig wallet with the second sig for an on-line vendor of a service.  I am planning to fund the wallet soon but wanted to ask this:  If the vendor does not provide the service, how can I recover my bitcoin? Or is it stuck in the wallet forever?

**Comment by aikkyu35** [comment]
#738

**Comment by bbob1234** [comment]
aikkyu - what does that mean?

**Comment by Nutnutneet** [comment]
Is sue

**Comment by matiu** [comment]
It will be on the wallet for ever. For that use case you need a 2-3 wallet, in which the 3th key is in held by an arbitrator.
