### ISSUE TITLE
Can I run BWS without running standalone Bitcore?

### ISSUE THREAD

**Issue by wrinkl3** [bitpay/bitcore-wallet-service#770]
Does BWS actually depend on the Bitcore node for any of the bitcoin functionality, or can it act as an SPV wallet on its own?

**Comment by arruah** [comment]
You can use another full node. You need to specify the ip address and port in the settings file.

**Comment by matiu** [comment]
you can use it pointing to any public Insight installation.

**Comment by RomaZavalnyUk** [comment]
Issue moved to [bitpay/android-sdk-sample #5](https://github.com/bitpay/android-sdk-sample/issues/5) via [**ZenHub**](https://www.zenhub.com/)

**Comment by martindale** [comment]
> You can use another full node. You need to specify the ip address and port in the settings file.
@arruah can you provide a sample?  It seems documentation around this has been removed.
