### ISSUE TITLE
1JM2y568RHGC6qeTXJdzP4xtbDTcSEXZHA?amount=0.9010597400000001024

### ISSUE THREAD

**Issue by Arti2102** [bitpay/bitcore-wallet-service#775]
1JM2y568RHGC6qeTXJdzP4xtbDTcSEXZHA?amount=0.9010597400000001024

**Comment by nutly** [comment]
nut

เมื่อ 17 มี.ค. 2018 22:12 "Arti2102" <notifications@github.com> เขียนว่า

**Comment by Arti2102** [comment]
https://twitter.com/arturzdanowicz/status/974004947451858945?s=12

**Comment by Arti2102** [comment]
062685

**Comment by Arti2102** [comment]
https://twitter.com/arturzdanowicz/status/974004947451858945?s=12
