### ISSUE TITLE
Can I use UTXOs from different addresses?

### ISSUE THREAD

**Issue by toknT** [bitpay/bitcore-wallet-service#792]
I am a beginner of developing bitcoin.

I explained to my boss , it's impossible to use **UTXOs from different addresses because due to different pvriverty keys are signed it will fail in script `OP_EQUALVERIFY`**, bu he still wants me to do it.

Is it possible to use UTXOs from different address with different priverty keys in the api?If no is there any other way to do it?

**Comment by dabura667** [comment]
Yes.

**Comment by toknT** [comment]
@dabura667 , sorry, I still don't understand how can I do this, Are there any articles about this? 

I search 'multi UTXO from different address' 'different addresses UTXO' and so on in Google, but can't get any useful result.

**Comment by dabura667** [comment]
There are no specific articles about it, no.

Just sign with two keys.

Did you try?

If so, show us your code. Use some testnet coins. Give us the utxo info.

**Comment by toknT** [comment]
@dabura667 sorry, I make a mistake ,get wrong priverty key to sign .
